version: '3.9'
services:
  my-sql:
    image: mysql:8.0.31
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456a@
      MYSQL_DATABASE: tbl_movies
      MYSQL_USER: movie
      MYSQL_PASSWORD: 123456a@
    volumes:
      - ./data/mysql:/var/lib/mysql  